version: '3'
services:
########## ##########
  dev:
    container_name: ge-dev
    image: ge-test:latest
    volumes:
      - ../project:/home/project
      - ../data:/home/data
    ports:
      - "8888:8888"
    env_file:
      - ./config/server.env